direction: right
OtherChains: Other Chains{
  "UserContract": Smart Contract
  "NSC": Name Service Contract

  UserContract -> NSC: resolve()
  NSC -> Event:  Emit 
  NSC -> UserContract:  Callback
}

Mycel: Mycel{
  Resolver {
  EventHandler: Event Handler
  IBCHandler: IBC Handler

  EventHandler -> Resolver : Resolve domain name
  Resolver -> EventHandler

  IBCHandler -> Resolver : Resolve domain name
  Resolver -> IBCHandler
  }
  Epochs {
  }
  Incentives {
    IncentiveStore: Incentive Store
    DistributeRewards: Distribute Rewards

    IncentiveStore <- DistributeRewards: Get rewards to distribute

  }
  Registry {
    DomainStore: Domain Store
    RegisterDomain: Register Domain
    UpdateRecord: Update Record

    RegisterDomain -> DomainStore: Register domain
    UpdateRecord -> DomainStore: Update record
  }

  Resolver.Resolver -> Registry.DomainStore: Resolve domain name
  Registry.RegisterDomain -> Incentives: Regsitration fee
  Registry.RegisterDomain -> Incentives.IncentiveStore: Store rewards for each period
  Epochs -> Incentives.DistributeRewards: Distrbute rewards on every period
  Epochs -> Resolver.EventHandler 
}


User: {
  shape: image
  icon: https://icons.terrastruct.com/essentials%2F359-users.svg
}

Validator: {
  shape: image
  icon: https://icons.terrastruct.com/essentials%2F359-users.svg
}
# User -> OtherChains.userContract : Resolve via smart contract
# User -> Mycel.Resolver.IBCHandler : Resolve via IBC

User -> Mycel.Registry.RegisterDomain : Register domain
User -> Mycel.Registry.UpdateRecord : Update record

OtherChains.Event <-> Mycel.Resolver.eventHandler :  Hook
Mycel.Resolver.EventHandler -> OtherChains.NSC : Result
Mycel.Incentives.DistributeRewards -> Validator :Reward
