direction: right
anotherBlockchain: Chain A{
  "userContract": Smart Contract
  "NRC": Name Resolution Contract

  userContract -> NRC: 1. resolve()
  NRC -> userContract: 5. Callback
}

mycel{
  eventHandler: Event Handler
  Resolver

  eventHandler -> Resolver : 3. Resolve domain name
  Resolver -> eventHandler

}
EOA.shape:person
EOA -> anotherBlockchain.userContract 
anotherBlockchain.NRC -> mycel.eventHandler : 2. Emit onRequest
mycel.eventHandler -> anotherBlockchain.NRC: 4. Response


