mycel: mycel {
  DNS: mycel DNS server
  Registry: mycel Regsitry

  DNS -> Registry
}

otherChain: Other Chains {
  NSC: mycel Name Service Contract
}
otherChain.NSC -> mycel.Registry

"user".shape: person
"example.cel".shape: page

user -> "example.cel": example.cel?
"example.cel" -> mycel.DNS: DNS
"example.cel" -> otherChain.NSC: EVM,Move...
mycel.Registry-> "1.1.1.1" : Website
mycel.Registry-> "mail.example.com" : Mail Server
mycel.Registry-> "3Fzbhgie...igbGUUZv": BTC
mycel.Registry-> "0x0FaB94...D9249dA": EVM
mycel.Registry-> "cosmos:ie...igbG4Zv": Cosmos Hub
mycel.Registry-> "ipfs://ivo": IPFS
mycel.Registry-> "https://~.icp0.io": ICP
mycel.Registry->"...": Other addresses
