mycel: mycel Network {
  DNS: mycel DNS server
  Registrar: mycel Regstrar

  DNS -> Registrar
}

otherChain: Other Chains {
  NSC: mycel Name Service Contract
}
otherChain.NSC -> mycel.Registrar

"user".shape: person
"your.eth".shape: page

user -> "your.eth": your.eth?
"your.eth" -> mycel.DNS: DNS
"your.eth" -> otherChain.NSC: EVM,Move...
mycel.Registrar-> "your.website" : Website
mycel.Registrar-> "3Fzbhgie...igbGUUZv": BTC
mycel.Registrar-> "0x0FaB94...D9249dA": EVM
mycel.Registrar-> "cosmos:ie...igbG4Zv": Cosmos Hub
mycel.Registrar->"...": Other addresses
